name: Java CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Oop Project

    steps:
    - name: Code checkout karo
      uses: actions/checkout@v4

    - name: Java 25 setup karo
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Build karo
      run: mvn clean install

    - name: Tests chalao
      run: mvn test